version: '3.8'
services:
  bot:
    build: .
    command: python -m bot.main
    env_file:
      - .env
    volumes:
      - ./musicbot.sqlite:/app/musicbot.db
    restart: unless-stopped
  dashboard:
    build: .
    command: uvicorn dashboard.app:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "43827:8000"
    volumes:
      - ./musicbot.sqlite:/app/musicbot.db
    restart: unless-stopped 